### ISSUE TITLE
Add sentence-transformers all mini and mpnet to staging init

### ISSUE THREAD

**Issue by erob123** [MIT-AI-Accelerator/c3po-model-server#52]
all mini: 
```
{
  "sha256": "e32a0f4e27e7e89b7fea160d213e79d8567a1124ff12a80ec0356dc5e2c45bfb",
  "model_type": "sentence_transformers",
  "model_name": "all-MiniLM-L6-v2",
  "id": "88adcb56-b77e-4d4f-ba1d-0cf958bae2a7",
  "uploaded": true,
  "version": 1,
  "originated_from": "app"
}
```

need to upload mpnet and add here too

**Comment by lshinggg** [comment]
mpnet

{
  "sha256": "9a769a6362cd525e4da7211fd569772b94db2b852c8c0c876ac9aed32b8f66c7",
  "model_type": "sentence_transformers",
  "model_name": "all-mpnet-base-v2",
  "id": "1dcf5836-4b15-43a9-b2f9-6d57e1f03662",
  "uploaded": true,
  "version": 1,
  "originated_from": "app"
}

**Comment by lshinggg** [comment]
{
  "sha256": "728ab8f6faf6410bd06e5eecffe26822028262d5307d6626ab547486602c06c9",
  "model_type": "cross_encoders",
  "model_name": "ms-marco-TinyBERT-L-6",
  "id": "e494875f-c13e-41c5-acb8-6db751f66cc7",
  "uploaded": true,
  "version": 2,
  "originated_from": "app"
}
